### ISSUE TITLE
[WARNING] DON'T DO THAT

### ISSUE THREAD

**Issue by iagolaguna** [johannlucas/ionicStudy#1]
Use ReactNative instead or use native language like swift,java,kotlin or even Objective-C

**Comment by johannlucas** [comment]
Appreciated, but still think that the study is worth it and maybe it's a good option for quick applications

**Comment by iagolaguna** [comment]
What is the reason to delivery an hybrid applications for your clients? When you can delivery an native applications basically doing the same, it's not a big journey ionic to react, ionic use Angular to build your screen's and use cordova plugins to take use of native capabilities

**Comment by johannlucas** [comment]
Even when the core of the application isn't performance or use of the hardware components like the camera or motion sensor? Let's suppose you need to develop a simple application where your customer will just check an inventory and your access to the data is a web api, even on this case IONIC isn't worth?

I'm completely dumb about mobile development by the way, any information it's great

**Comment by iagolaguna** [comment]
is so simple you can build a PWA(progressive web application), check the documentation and  check this web site https://pwa.rocks/t
about ionic, i have a lagacy project in my company using one version of ionic 2, and i'm having headaches always when i need to deploy a new version, but it's a choice to develop an app, but i don't know any success case  about an app build in ionic 2, but ReactNative you have Airbnb, Instagram, Messenger i can't tell you more about ReactNative, because i don't use them yet but many coworkers tell me it's a good choice to take.

If you have any experience building apps and  any experience about web frameworks, i recommend you take React, if you have experience with Angular  i say to you can take Ionic to start, but i recommend you see about ReactNative later, he can open your eyes.

**Comment by johannlucas** [comment]
It's possible to make a pwa with Ionic, but I got you and I consider the idea of using React. Ionic have big users too, just see the website https://ionicframework.com/
I will see React after Ionic for sure, but don't be so rude with Ionic, he's beautiful too :)
Sorry for the wait and thanks!
